name: Server Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Navigate to server directory
        run: cd server
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
